version: "3.5"

services:
  database:
    image: postgres:9.6
    container_name: forum
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=forum
      - POSTGRES_PASSWORD=forum
      - POSTGRES_DB=forum
